spring.application.name=todo-app
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://${MYSQL_HOST:localhost}:5432/todo_app
spring.datasource.username=postgres
spring.datasource.password=1234567890
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.show-sql: true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.security.user.name=admin2
spring.security.user.password==admin2